# Generated by Django 4.1 on 2022-08-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0002_remove_recipe_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
