# Generated by Django 4.1 on 2022-08-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0006_musclegroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('shortDescription', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('primaryImage', models.ImageField(upload_to='')),
                ('explanatoryImage', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='musclegroup',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
