# Generated by Django 4.1 on 2022-08-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0008_exercise_musclegroup_alter_exercise_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='shortDescription',
            field=models.CharField(max_length=250),
        ),
    ]
