# Generated by Django 4.1 on 2022-08-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0010_answer_test_testuser_fitnessuser_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='questionQuantity',
            field=models.IntegerField(),
        ),
    ]
