# Generated by Django 4.1 on 2022-08-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0011_alter_test_questionquantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='possibleAnswers',
            field=models.ManyToManyField(blank=True, null=True, related_name='possible_answers', to='fitness_app.answer'),
        ),
    ]
