# Generated by Django 4.1 on 2022-09-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0013_alter_testuser_fitnessuser_alter_testuser_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
