# Generated by Django 4.1 on 2022-09-03 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0014_alter_exercise_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='theAnswer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='the_answer', serialize=False, to='fitness_app.answer'),
        ),
    ]
