# Generated by Django 4.1 on 2022-09-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0018_alter_fact_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
