name: Docker Build and Push

on:
  push:
    branches:
      - develop_with_postgresql

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t add5/fitness:latest .

      - name: Push Docker image to Docker Hub
        run: docker push add5/fitness:latest

      - name: Start containers with Docker Compose
        run: docker-compose -f ${{ github.workspace }}/docker-compose.yml up -d --env-file .env

      - name: Check Docker container status
        run: docker-compose -f ${{ github.workspace }}/docker-compose.yml ps --env-file .env
